/**
 * Closed event vocabulary (N2): 40 types. Unknown type fails closed.
 * Each event type declares the payload schema it carries; the reducer owns
 * which (stage, eventType) pairs are legal.
 */
export const EventType = {
    // Mission lifecycle
    MISSION_CREATED: "MISSION_CREATED",
    MISSION_ABORTED: "MISSION_ABORTED",
    MISSION_FAILED: "MISSION_FAILED",
    MISSION_CLOSED: "MISSION_CLOSED",
    // Policy
    POLICY_SCREEN_STARTED: "POLICY_SCREEN_STARTED",
    POLICY_SCREEN_COMPLETED: "POLICY_SCREEN_COMPLETED",
    // Recon
    RECON_STARTED: "RECON_STARTED",
    RECON_COMPLETED: "RECON_COMPLETED",
    // Planning
    PLAN_PROPOSED: "PLAN_PROPOSED",
    PLAN_CHALLENGED: "PLAN_CHALLENGED",
    PLAN_REVISED: "PLAN_REVISED",
    // Approvals
    APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
    APPROVAL_RECORDED: "APPROVAL_RECORDED",
    APPROVAL_EXPIRED: "APPROVAL_EXPIRED",
    // Execution
    IMPLEMENTATION_STARTED: "IMPLEMENTATION_STARTED",
    IMPLEMENTATION_COMPLETED: "IMPLEMENTATION_COMPLETED",
    REVISION_REQUESTED: "REVISION_REQUESTED",
    REVISION_COMPLETED: "REVISION_COMPLETED",
    // Quality
    VERIFICATION_COMPLETED: "VERIFICATION_COMPLETED",
    TECHNICAL_REVIEW_COMPLETED: "TECHNICAL_REVIEW_COMPLETED",
    DOCUMENTATION_COMPLETED: "DOCUMENTATION_COMPLETED",
    FINAL_GATE_COMPLETED: "FINAL_GATE_COMPLETED",
    // Artifacts
    ARTIFACT_FINALIZED: "ARTIFACT_FINALIZED",
    ARTIFACT_REJECTED: "ARTIFACT_REJECTED",
    // Tools
    TOOL_INVOCATION_PREPARED: "TOOL_INVOCATION_PREPARED",
    TOOL_INVOCATION_DISPATCHED: "TOOL_INVOCATION_DISPATCHED",
    TOOL_INVOCATION_SETTLED: "TOOL_INVOCATION_SETTLED",
    TOOL_INVOCATION_FAILED: "TOOL_INVOCATION_FAILED",
    TOOL_INVOCATION_OUTCOME_UNKNOWN: "TOOL_INVOCATION_OUTCOME_UNKNOWN",
    // Public actions (reserved; disabled in v0.1.1)
    PUBLIC_ACTION_PREPARED: "PUBLIC_ACTION_PREPARED",
    PUBLIC_ACTION_DISPATCHED: "PUBLIC_ACTION_DISPATCHED",
    PUBLIC_ACTION_RECONCILED: "PUBLIC_ACTION_RECONCILED",
    PUBLIC_ACTION_FAILED: "PUBLIC_ACTION_FAILED",
    // Budgets
    BUDGET_RESERVED: "BUDGET_RESERVED",
    BUDGET_SETTLED: "BUDGET_SETTLED",
    BUDGET_RELEASED: "BUDGET_RELEASED",
    BUDGET_TOPUP_APPROVED: "BUDGET_TOPUP_APPROVED",
    // Checkpoints
    CHECKPOINT_WRITTEN: "CHECKPOINT_WRITTEN",
    RECOVERY_STARTED: "RECOVERY_STARTED",
    RECOVERY_COMPLETED: "RECOVERY_COMPLETED",
};
export const ALL_EVENT_TYPES = Object.values(EventType);
export const EVENT_TYPE_COUNT = ALL_EVENT_TYPES.length;
/** Closed event types whose payload describes a public action (A33). */
export const PUBLIC_ACTION_EVENT_TYPES = new Set([
    EventType.PUBLIC_ACTION_PREPARED,
    EventType.PUBLIC_ACTION_DISPATCHED,
    EventType.PUBLIC_ACTION_RECONCILED,
    EventType.PUBLIC_ACTION_FAILED,
]);
//# sourceMappingURL=vocabulary.js.map