/**
 * Closed event vocabulary (N2): 40 types. Unknown type fails closed.
 * Each event type declares the payload schema it carries; the reducer owns
 * which (stage, eventType) pairs are legal.
 */
export declare const EventType: {
    readonly MISSION_CREATED: "MISSION_CREATED";
    readonly MISSION_ABORTED: "MISSION_ABORTED";
    readonly MISSION_FAILED: "MISSION_FAILED";
    readonly MISSION_CLOSED: "MISSION_CLOSED";
    readonly POLICY_SCREEN_STARTED: "POLICY_SCREEN_STARTED";
    readonly POLICY_SCREEN_COMPLETED: "POLICY_SCREEN_COMPLETED";
    readonly RECON_STARTED: "RECON_STARTED";
    readonly RECON_COMPLETED: "RECON_COMPLETED";
    readonly PLAN_PROPOSED: "PLAN_PROPOSED";
    readonly PLAN_CHALLENGED: "PLAN_CHALLENGED";
    readonly PLAN_REVISED: "PLAN_REVISED";
    readonly APPROVAL_REQUESTED: "APPROVAL_REQUESTED";
    readonly APPROVAL_RECORDED: "APPROVAL_RECORDED";
    readonly APPROVAL_EXPIRED: "APPROVAL_EXPIRED";
    readonly IMPLEMENTATION_STARTED: "IMPLEMENTATION_STARTED";
    readonly IMPLEMENTATION_COMPLETED: "IMPLEMENTATION_COMPLETED";
    readonly REVISION_REQUESTED: "REVISION_REQUESTED";
    readonly REVISION_COMPLETED: "REVISION_COMPLETED";
    readonly VERIFICATION_COMPLETED: "VERIFICATION_COMPLETED";
    readonly TECHNICAL_REVIEW_COMPLETED: "TECHNICAL_REVIEW_COMPLETED";
    readonly DOCUMENTATION_COMPLETED: "DOCUMENTATION_COMPLETED";
    readonly FINAL_GATE_COMPLETED: "FINAL_GATE_COMPLETED";
    readonly ARTIFACT_FINALIZED: "ARTIFACT_FINALIZED";
    readonly ARTIFACT_REJECTED: "ARTIFACT_REJECTED";
    readonly TOOL_INVOCATION_PREPARED: "TOOL_INVOCATION_PREPARED";
    readonly TOOL_INVOCATION_DISPATCHED: "TOOL_INVOCATION_DISPATCHED";
    readonly TOOL_INVOCATION_SETTLED: "TOOL_INVOCATION_SETTLED";
    readonly TOOL_INVOCATION_FAILED: "TOOL_INVOCATION_FAILED";
    readonly TOOL_INVOCATION_OUTCOME_UNKNOWN: "TOOL_INVOCATION_OUTCOME_UNKNOWN";
    readonly PUBLIC_ACTION_PREPARED: "PUBLIC_ACTION_PREPARED";
    readonly PUBLIC_ACTION_DISPATCHED: "PUBLIC_ACTION_DISPATCHED";
    readonly PUBLIC_ACTION_RECONCILED: "PUBLIC_ACTION_RECONCILED";
    readonly PUBLIC_ACTION_FAILED: "PUBLIC_ACTION_FAILED";
    readonly BUDGET_RESERVED: "BUDGET_RESERVED";
    readonly BUDGET_SETTLED: "BUDGET_SETTLED";
    readonly BUDGET_RELEASED: "BUDGET_RELEASED";
    readonly BUDGET_TOPUP_APPROVED: "BUDGET_TOPUP_APPROVED";
    readonly CHECKPOINT_WRITTEN: "CHECKPOINT_WRITTEN";
    readonly RECOVERY_STARTED: "RECOVERY_STARTED";
    readonly RECOVERY_COMPLETED: "RECOVERY_COMPLETED";
};
export type EventType = (typeof EventType)[keyof typeof EventType];
export declare const ALL_EVENT_TYPES: readonly EventType[];
export declare const EVENT_TYPE_COUNT: number;
/** Closed event types whose payload describes a public action (A33). */
export declare const PUBLIC_ACTION_EVENT_TYPES: ReadonlySet<EventType>;
